#server:
#  port: 8070
#eureka:
#  client:
#    register-with-eureka: true
#spring:
#  application:
#    name: AUTH-SERVICE
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/buildlive_user
#    username: root
#    password: '@77SUDHA'
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQLDialect
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: 'buildlive360@gmail.com'
#    password: '@77SUDHA'
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

spring:
  application:
    name: "auth"
  profiles:
    active: "service"
  config:
    import: "optional:configserver:http://13.127.132.74:8888"
#  zipkin:
#    base:
#      url: http://127.0.0.1:9411/




#management:
#  health:
#    circuitbreakers:
#      enabled: true
#    endpoints:
#      web:
#        exposure:
#          include: health
#    endpoint:
#      health:
#        show-details: always
#
#resilience4j:
#  circuitbreaker:
#    instances:
#      auth-service:
#        registerHealthIndicator: true
#        eventConsumerBufferSize: 10
#        failureRateThreshold: 50
#        minimumNumberOfCalls: 5
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        waitDurationInOpenState: 5s
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowSize: 10
#        slidingWindowType: COUNT_BASED

















